/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample.java.app;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        //assertNull(classUnderTest.getGreeting());
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
        //System.out.println("Test-successful");
    }
}
