/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample.java.app;

public class App {

    //Addition
    public final int add(int a, int b) {
        return a + b;
    }

    //Subtraction
    public final int subtract(int a, int b) {
        return a - b;
    }

    //Multiplication
    public final int multiply(int a, int b) {
        return a * b;
    }

    //Division
    public final int divide(int a, int b) {
        if (b == 0) {
            throw new IllegalArgumentException("Cannot divide by zero");
        }
        return a / b;
    }

    public static void main(String[] args) {
        App app = new App();
        System.out.println(app.add(5, 3));
        System.out.println(app.subtract(5, 3));
        System.out.println(app.multiply(5, 3));
        System.out.println(app.divide(6, 3));
    }
}
