# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  checkout:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

  setup:
    needs: checkout
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Gradle Setup
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.1.1

  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - name: Build with Gradle
      run: gradle build

  tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Run tests
      run: gradle test
    - name: Publish test reports
      uses: actions/upload-artifact@v2
      with:
        name: Test Reports
        path: app/build/reports/tests/test/index.html
        
  publish:
    needs: tests
    runs-on: ubuntu-latest

    steps:
    - name: Run tests
      run: gradle test
    - name: Publish test reports
      uses: actions/upload-artifact@v2
      with:
        name: Test Reports
        path: app/build/reports/tests/test/index.html      